spring.datasource.url=jdbc:postgresql://localhost:3000/blunterest-db
spring.datasource.password=password
spring.datasource.username=bluntpin

s3.access-key=${S3_ACCESS}
s3.secret-key=${S3_SECRET}
s3.bucket-name=blunterest-images
s3.storage-url=https://storage.yandexcloud.net
s3.region=ru-central1